@section('title', 'Уведомления - SOCNET SMM')
@extends('user.app.layout')

@section('content')
    <div class="notifications-page">
        <!-- Page Header -->
        <div class="page-header">
            <h1 class="page-title">{{ __('Уведомления') }}</h1>
        </div>

        <!-- Notifications Stats -->
        <div class="notifications-stats">
            <div class="stats-left">
                <span class="notifications-count">{{ __('Всего уведомлений:') }} <strong
                        id="notificationsCount">0</strong></span>
            </div>
            @if (helperClass()->getUserUnreadNotificationsCount() > 0)
                <div class="stats-actions">
                    <button type="button" class="action-btn mark-all-read-btn" id="markAllReadBtn"
                        title="{{ __('Отметить все как прочитанные') }}">
                        <i class="fas fa-check-double"></i>
                        <span class="btn-text">{{ __('Прочитать все') }}</span>
                    </button>
                    <button type="button" class="action-btn delete-all-btn" id="deleteAllBtn"
                        title="{{ __('Удалить все уведомления') }}">
                        <i class="fas fa-trash-alt"></i>
                        <span class="btn-text">{{ __('Удалить все') }}</span>
                    </button>
                </div>
            @endif
        </div>

        <!-- Notifications List Section -->
        <div class="notifications-list-section">
            <!-- Notifications Container -->
            <div class="notifications-container" id="notificationsContainer">
                <!-- Notifications will be loaded here by JavaScript -->
            </div>

            <!-- Empty State -->
            <div class="empty-state" id="notificationsEmptyState" style="display: none;">
                <div class="empty-icon">
                    <i class="fas fa-bell-slash"></i>
                </div>
                <h3 class="empty-title">{{ __('Нет уведомлений') }}</h3>
                <p class="empty-description">{{ __('Здесь будут отображаться все ваши уведомления') }}</p>
            </div>

            <!-- Loading State -->
            <div class="loading-state" id="notificationsLoadingState">
                <div class="loading-spinner"></div>
                <p>{{ __('Загрузка уведомлений...') }}</p>
            </div>

            <!-- Pagination -->
            <div class="pagination-section" id="notificationsPaginationSection" style="display: none;">
                {{-- <div class="pagination-info">
                <span id="notificationsPaginationInfo">{{ __('Показано 1-20 из 0') }}</span>
            </div> --}}
                <div class="pagination-controls" id="notificationsPaginationControls">
                    <!-- Pagination buttons will be generated by JavaScript -->
                </div>
            </div>
        </div>
    </div>

    @push('js')
        <script type="text/javascript" src="{{ mix('assets/user/js/pages/notifications.js') }}"></script>
    @endpush

@endsection
