@section('title', 'Обновления - SOCNET SMM')
@extends('user.app.layout')

@section('content')
<div class="updates-page">
    <!-- Page Header -->
    <div class="page-header">
        <h1 class="page-title">{{ __('Обновления') }}</h1>
    </div>

    <!-- Updates Stats -->
    <div class="updates-stats">
        <span class="updates-count">{{ __('Всего записей:') }} <strong id="updatesCount">0</strong></span>
    </div>

    <!-- Updates List -->
    <div class="updates-list-section">
        <!-- Updates Container -->
        <div class="updates-container" id="updatesContainer">
            <!-- Updates will be loaded here by JavaScript -->
        </div>

        <!-- Empty State -->
        <div class="empty-state" id="updatesEmptyState" style="display: none;">
            <div class="empty-icon">
                <i class="fas fa-info-circle"></i>
            </div>
            <h3 class="empty-title">{{ __('Нет обновлений') }}</h3>
            <p class="empty-description">{{ __('В данный момент нет новых обновлений. Следите за этой страницей для получения актуальной информации.') }}</p>
        </div>

        <!-- Loading State -->
        <div class="loading-state" id="updatesLoadingState">
            <div class="loading-spinner"></div>
            <p>{{ __('Загрузка обновлений...') }}</p>
        </div>

        <!-- Pagination -->
        <div class="pagination-section" id="updatesPaginationSection" style="display: none;">
            <div class="pagination-info">
                <span id="updatesPaginationInfo">{{ __('Показано 1-20 из 50') }}</span>
            </div>
            <div class="pagination-controls" id="updatesPaginationControls">
                <!-- Pagination buttons will be generated by JavaScript -->
            </div>
        </div>
    </div>
</div>

@push('js')
    <script type="text/javascript" src="{{ mix('assets/user/js/pages/updates.js') }}"></script>
@endpush

@endsection
